export const structure = {
  name: 'My Character',
  portrait: null,
  level: 1,
  xp: 0,
  heroes: 0,
  ancestry: null,
  heritage: null,
  background: null,
  class: null,
  size: null,
  alignment: null,
  traits: [],
  deity: null,
  abilities: {
    str: 10,
    dex: 10,
    con: 10,
    int: 10,
    wis: 10,
    cha: 10,
  },
  hp: {
    current: 0,
  },
  proficiencies: {
    saves: {
      fortitude: 0,
      reflex: 0,
      will: 0,
    },
    class: 0,
    perception: 0,
    skills: {
      acrobatics: 0,
      arcana: 0,
      athletics: 0,
      crafting: 0,
      deception: 0,
      diplomacy: 0,
      intimidation: 0,
      lore: [
        {
          name: '',
          proficiency: 0,
        },
      ],
      medicine: 0,
      nature: 0,
      occultism: 0,
      performance: 0,
      religion: 0,
      society: 0,
      stealth: 0,
      survival: 0,
      thievery: 0,
    },
    armor: {
      unarmored: 0,
      light: 0,
      medium: 0,
      heavy: 0,
      other: [
        {
          name: 'Other Armor',
          proficiency: 0,
        },
      ],
    },
    weapons: {
      unarmed: 0,
      simple: 0,
      martial: 0,
      other: [
        {
          name: 'Other Weapon',
          proficiency: 0,
        },
      ],
    },
    spells: {
      attack: 0,
      dc: 0,
      traditions: [],
    },
  },
  languages: ['common'],
  conditions: [],
  feats: {
    ancestry: [],
    skill: [],
    class: [],
    general: [],
  },
  inventory: [],
};

export const spells = {
  attack: 0,
  dc: 0,
  traditions: [],
  preparation: {
    prepared: false,
    spontaneous: false,
  },
  slots: {
    cantrip: 1,
    first: 0,
    second: 0,
    third: 0,
    fourth: 0,
    fifth: 0,
    sixth: 0,
    seventh: 0,
    eighth: 0,
    ninth: 0,
    tenth: 0,
  },
};
