root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:n/recommended
  - google
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
plugins:
  - import
  - prettier
  - svelte3
  - '@typescript-eslint'
env:
  browser: true
  node: true
  es6: true
  es2017: true
  es2020: true
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2022
  sourceType: module
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.json
  svelte3/typescript: true
overrides:
  - files:
      - '*.svelte'
    processor: svelte3/svelte3
rules:
  n/no-missing-import: off
  n/no-unpublished-import: off
